package whu.edu.cn.trajlab.query.query.basic;

import whu.edu.cn.trajlab.query.coprocessor.STCoprocessorQuery;
import whu.edu.cn.trajlab.db.condition.AbstractQueryCondition;
import whu.edu.cn.trajlab.db.condition.SpatialQueryCondition;
import whu.edu.cn.trajlab.db.condition.TemporalQueryCondition;
import whu.edu.cn.trajlab.db.database.DataSet;
import whu.edu.cn.trajlab.db.database.meta.IndexMeta;
import whu.edu.cn.trajlab.db.database.table.IndexTable;
import whu.edu.cn.trajlab.db.enums.IndexType;
import whu.edu.cn.trajlab.db.enums.TemporalQueryType;
import whu.edu.cn.trajlab.db.index.RowKeyRange;
import whu.edu.cn.trajlab.db.condition.SpatialTemporalQueryCondition;
import whu.edu.cn.trajlab.base.trajectory.Trajectory;
import whu.edu.cn.trajlab.query.coprocessor.autogenerated.QueryCondition;

import java.io.IOException;
import java.util.List;
import java.util.Map;

/**
 * @author xuqi
 * @date 2023/12/01
 */
public class SpatialTemporalQuery extends AbstractQuery {

  private boolean filterBeforeLookFullRow = true;

  public SpatialTemporalQuery(DataSet dataSet, AbstractQueryCondition abstractQueryCondition)
      throws IOException {
    super(dataSet, abstractQueryCondition);
  }

  public SpatialTemporalQuery(IndexTable indexTable, AbstractQueryCondition abstractQueryCondition)
      throws IOException {
    super(indexTable, abstractQueryCondition);
  }

  public SpatialTemporalQuery(
      IndexTable indexTable,
      AbstractQueryCondition abstractQueryCondition,
      boolean filterBeforeLookFullRow)
      throws IOException {
    super(indexTable, abstractQueryCondition);
    this.filterBeforeLookFullRow = filterBeforeLookFullRow;
  }

  @Override
  public List<Trajectory> executeQuery(List<RowKeyRange> rowKeyRanges) throws IOException {
    List<QueryCondition.Range> ranges = rowKeyRangeToProtoRange(rowKeyRanges);
    SpatialTemporalQueryCondition spatialTemporalQueryCondition =
        (SpatialTemporalQueryCondition) abstractQueryCondition;
    SpatialQueryCondition spatialQueryCondition =
        spatialTemporalQueryCondition.getSpatialQueryCondition();
    TemporalQueryCondition temporalQueryCondition =
        spatialTemporalQueryCondition.getTemporalQueryCondition();
    List<QueryCondition.TemporalQueryWindow> temporalQueryWindows =
        IDTemporalQuery.buildProtoTemporalWindows(temporalQueryCondition);
    QueryCondition.QueryRequest spatialTemporalQueryRequest =
        QueryCondition.QueryRequest.newBuilder()
            .addAllRange(ranges)
            .setSt(
                QueryCondition.STQueryRequest.newBuilder()
                    .setSpatialQueryType(
                        spatialQueryCondition.getQueryType()
                                == SpatialQueryCondition.SpatialQueryType.CONTAIN
                            ? QueryCondition.QueryType.CONTAIN
                            : QueryCondition.QueryType.INTERSECT)
                    .setSpatialQueryWindow(
                        QueryCondition.SpatialQueryWindow.newBuilder()
                            .setWkt(spatialQueryCondition.getQueryWindowWKT()))
                    .setTemporalQueryType(
                        temporalQueryCondition.getTemporalQueryType() == TemporalQueryType.CONTAIN
                            ? QueryCondition.QueryType.CONTAIN
                            : QueryCondition.QueryType.INTERSECT)
                    .setTemporalQueryWindows(
                        QueryCondition.TemporalQueryWindows.newBuilder()
                            .addAllTemporalQueryWindow(temporalQueryWindows)
                            .build())
                    .setFilterBeforeLookFullRow(filterBeforeLookFullRow)
                    .build())
            .build();

    return STCoprocessorQuery.executeQuery(targetIndexTable, spatialTemporalQueryRequest);
  }

  @Override
  public IndexMeta findBestIndex() {
    Map<IndexType, List<IndexMeta>> map = dataSet.getDataSetMeta().getAvailableIndexes();
    // find a st index
    List<IndexMeta> indexList = null;
    if (map.containsKey(IndexType.TXZ2)) {
      indexList = map.get(IndexType.TXZ2);
    } else if (map.containsKey(IndexType.XZ2T)) {
      indexList = map.get(IndexType.XZ2T);
    }
    if (indexList != null) {
      return IndexMeta.getBestIndexMeta(indexList);
    }
    // TODO: 直接抛异常，禁止全表扫描
    // no st index so we will do a full table scan, we select a main index.
    return dataSet.getDataSetMeta().getCoreIndexMeta();
  }

  @Override
  public String getQueryInfo() {
    return abstractQueryCondition.getConditionInfo();
  }
}
