package whu.edu.cn.trajlab.query.query.basic;

import whu.edu.cn.trajlab.query.coprocessor.STCoprocessorQuery;
import whu.edu.cn.trajlab.db.condition.AbstractQueryCondition;
import whu.edu.cn.trajlab.db.condition.TemporalQueryCondition;
import whu.edu.cn.trajlab.db.database.DataSet;
import whu.edu.cn.trajlab.db.database.meta.IndexMeta;
import whu.edu.cn.trajlab.db.database.table.IndexTable;
import whu.edu.cn.trajlab.db.datatypes.TimeLine;
import whu.edu.cn.trajlab.db.enums.IndexType;
import whu.edu.cn.trajlab.db.enums.TemporalQueryType;
import whu.edu.cn.trajlab.db.index.RowKeyRange;
import org.apache.spark.api.java.JavaRDD;
import whu.edu.cn.trajlab.base.trajectory.Trajectory;
import whu.edu.cn.trajlab.query.coprocessor.autogenerated.QueryCondition;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * @author xuqi
 * @date 2023/12/11
 */
public class TemporalQuery extends AbstractQuery {

  public TemporalQuery(DataSet dataSet, AbstractQueryCondition abstractQueryCondition) {
    super(dataSet, abstractQueryCondition);
  }

  public TemporalQuery(IndexTable indexTable, AbstractQueryCondition abstractQueryCondition)
      throws IOException {
    super(indexTable, abstractQueryCondition);
  }

  @Override
  public List<RowKeyRange> getIndexRanges() throws IOException {
    setupTargetIndexTable();
    return targetIndexTable.getIndexMeta().getIndexStrategy().getScanRanges(abstractQueryCondition);
  }

  @Override
  public List<Trajectory> executeQuery() throws IOException {
    List<RowKeyRange> rowKeyRanges = getIndexRanges();
    return executeQuery(rowKeyRanges);
  }

  @Override
  public JavaRDD<Trajectory> query() throws IOException {
    return null;
  }

  @Override
  public List<Trajectory> executeQuery(List<RowKeyRange> rowKeyRanges) throws IOException {
    List<QueryCondition.Range> ranges = rowKeyRangeToProtoRange(rowKeyRanges);
    TemporalQueryCondition temporalQueryCondition = (TemporalQueryCondition) abstractQueryCondition;
    List<QueryCondition.TemporalQueryWindow> temporalQueryWindows =
        buildProtoTemporalWindows(temporalQueryCondition);

    QueryCondition.QueryRequest timeQueryRequest =
        QueryCondition.QueryRequest.newBuilder()
            .setTemporalQueryType(
                temporalQueryCondition.getTemporalQueryType() == TemporalQueryType.CONTAIN
                    ? QueryCondition.QueryType.CONTAIN
                    : QueryCondition.QueryType.INTERSECT)
            .setTemporalQueryWindows(
                QueryCondition.TemporalQueryWindows.newBuilder()
                    .addAllTemporalQueryWindow(temporalQueryWindows)
                    .build())
            .addAllRange(ranges)
            .build();

    return STCoprocessorQuery.executeQuery(targetIndexTable, timeQueryRequest);
  }

  @Override
  public IndexMeta findBestIndex() {
    Map<IndexType, List<IndexMeta>> map = dataSet.getDataSetMeta().getAvailableIndexes();
    // find a time index
    List<IndexMeta> indexList = null;
    if (map.containsKey(IndexType.Temporal)) {
      indexList = map.get(IndexType.Temporal);
    }
    if (indexList != null) {
      return IndexMeta.getBestIndexMeta(indexList);
    }
    // no spatial index so we will do a full table scan, we select a main index.
    return dataSet.getDataSetMeta().getCoreIndexMeta();
  }

  @Override
  public String getQueryInfo() {
    return abstractQueryCondition.getConditionInfo();
  }

  public static List<QueryCondition.TemporalQueryWindow> buildProtoTemporalWindows(
      TemporalQueryCondition temporalQueryCondition) {
    List<QueryCondition.TemporalQueryWindow> temporalQueryWindows = new ArrayList<>();
    for (TimeLine queryWindow : temporalQueryCondition.getQueryWindows()) {
      QueryCondition.TemporalQueryWindow temporalQueryWindow =
          QueryCondition.TemporalQueryWindow.newBuilder()
              .setStartMs(queryWindow.getTimeStart().toEpochSecond())
              .setEndMs(queryWindow.getTimeEnd().toEpochSecond())
              .build();
      temporalQueryWindows.add(temporalQueryWindow);
    }
    return temporalQueryWindows;
  }
}
